<script lang="ts">
	import { _ } from 'svelte-i18n'
	import { Link } from 'svelte-navigator'
	import PalabrioLogo from '~/lib/components/PalabrioLogo.svelte'
</script>

<main>
	<header>
		<Link to="/"><h1><PalabrioLogo /></h1></Link>
		<Link to="/">{$_('action.back')}</Link>
	</header>

	<br />
	<br />

	<h1>Dictionaries</h1>
	<table>
		<tbody>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/bg"
						><code>dictionary-bg</code></a
					></td
				>
				<td>Bulgarian</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/bg/license"
						>(GPL-2.0 OR LGPL-2.1 OR MPL-1.1)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/br"
						><code>dictionary-br</code></a
					></td
				>
				<td>Breton</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/br/license"
						>(GPL-2.0 OR LGPL-2.1 OR MPL-1.1)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/ca"
						><code>dictionary-ca</code></a
					></td
				>
				<td>Catalan</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/ca/license"
						>(GPL-2.0 OR LGPL-2.1)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/ca-valencia"
						><code>dictionary-ca-valencia</code></a
					></td
				>
				<td>Catalan (Valencian)</td>
				<td
					><a
						href="/wooorm/dictionaries/blob/main/dictionaries/ca-valencia/license"
						>(GPL-2.0 OR LGPL-2.1)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/cs"
						><code>dictionary-cs</code></a
					></td
				>
				<td>Czech</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/cs/license"
						>GPL-2.0</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/da"
						><code>dictionary-da</code></a
					></td
				>
				<td>Danish</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/da/license"
						>(GPL-2.0 OR LGPL-2.1 OR MPL-1.1)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/de"
						><code>dictionary-de</code></a
					></td
				>
				<td>German</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/de/license"
						>(GPL-2.0 OR GPL-3.0)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/de-AT"
						><code>dictionary-de-at</code></a
					></td
				>
				<td>German (Austria)</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/de-AT/license"
						>(GPL-2.0 OR GPL-3.0)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/de-CH"
						><code>dictionary-de-ch</code></a
					></td
				>
				<td>German (Switzerland)</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/de-CH/license"
						>(GPL-2.0 OR GPL-3.0)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/el"
						><code>dictionary-el</code></a
					></td
				>
				<td>Modern Greek</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/el/license"
						>(GPL-2.0 OR LGPL-2.1 OR MPL-1.1)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/el-polyton"
						><code>dictionary-el-polyton</code></a
					></td
				>
				<td>Modern Greek (Polytonic Greek)</td>
				<td
					><a
						href="/wooorm/dictionaries/blob/main/dictionaries/el-polyton/license"
						>GPL-3.0</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/en"
						><code>dictionary-en</code></a
					></td
				>
				<td>English</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/en/license"
						>(MIT AND BSD)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/en-AU"
						><code>dictionary-en-au</code></a
					></td
				>
				<td>English (Australia)</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/en-AU/license"
						>(MIT AND BSD)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/en-CA"
						><code>dictionary-en-ca</code></a
					></td
				>
				<td>English (Canada)</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/en-CA/license"
						>(MIT AND BSD)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/en-GB"
						><code>dictionary-en-gb</code></a
					></td
				>
				<td>English (United Kingdom)</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/en-GB/license"
						>(MIT AND BSD)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/en-ZA"
						><code>dictionary-en-za</code></a
					></td
				>
				<td>English (South Africa)</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/en-ZA/license"
						>LGPL-2.1</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/eo"
						><code>dictionary-eo</code></a
					></td
				>
				<td>Esperanto</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/eo/license"
						>GPL-2.0</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es"
						><code>dictionary-es</code></a
					></td
				>
				<td>Spanish (or Castilian)</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es/license"
						>(GPL-3.0 OR LGPL-3.0 OR MPL-1.1)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-AR"
						><code>dictionary-es-ar</code></a
					></td
				>
				<td>Spanish (or Castilian; Argentina)</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-AR/license"
						>(GPL-3.0 OR LGPL-3.0 OR MPL-1.1)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-BO"
						><code>dictionary-es-bo</code></a
					></td
				>
				<td>Spanish (or Castilian; Bolivia)</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-BO/license"
						>(GPL-3.0 OR LGPL-3.0 OR MPL-1.1)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-CL"
						><code>dictionary-es-cl</code></a
					></td
				>
				<td>Spanish (or Castilian; Chile)</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-CL/license"
						>(GPL-3.0 OR LGPL-3.0 OR MPL-1.1)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-CO"
						><code>dictionary-es-co</code></a
					></td
				>
				<td>Spanish (or Castilian; Colombia)</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-CO/license"
						>(GPL-3.0 OR LGPL-3.0 OR MPL-1.1)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-CR"
						><code>dictionary-es-cr</code></a
					></td
				>
				<td>Spanish (or Castilian; Costa Rica)</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-CR/license"
						>(GPL-3.0 OR LGPL-3.0 OR MPL-1.1)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-CU"
						><code>dictionary-es-cu</code></a
					></td
				>
				<td>Spanish (or Castilian; Cuba)</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-CU/license"
						>(GPL-3.0 OR LGPL-3.0 OR MPL-1.1)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-DO"
						><code>dictionary-es-do</code></a
					></td
				>
				<td>Spanish (or Castilian; Dominican Republic)</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-DO/license"
						>(GPL-3.0 OR LGPL-3.0 OR MPL-1.1)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-EC"
						><code>dictionary-es-ec</code></a
					></td
				>
				<td>Spanish (or Castilian; Ecuador)</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-EC/license"
						>(GPL-3.0 OR LGPL-3.0 OR MPL-1.1)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-GT"
						><code>dictionary-es-gt</code></a
					></td
				>
				<td>Spanish (or Castilian; Guatemala)</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-GT/license"
						>(GPL-3.0 OR LGPL-3.0 OR MPL-1.1)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-HN"
						><code>dictionary-es-hn</code></a
					></td
				>
				<td>Spanish (or Castilian; Honduras)</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-HN/license"
						>(GPL-3.0 OR LGPL-3.0 OR MPL-1.1)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-MX"
						><code>dictionary-es-mx</code></a
					></td
				>
				<td>Spanish (or Castilian; Mexico)</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-MX/license"
						>(GPL-3.0 OR LGPL-3.0 OR MPL-1.1)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-NI"
						><code>dictionary-es-ni</code></a
					></td
				>
				<td>Spanish (or Castilian; Nicaragua)</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-NI/license"
						>(GPL-3.0 OR LGPL-3.0 OR MPL-1.1)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-PA"
						><code>dictionary-es-pa</code></a
					></td
				>
				<td>Spanish (or Castilian; Panama)</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-PA/license"
						>(GPL-3.0 OR LGPL-3.0 OR MPL-1.1)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-PE"
						><code>dictionary-es-pe</code></a
					></td
				>
				<td>Spanish (or Castilian; Peru)</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-PE/license"
						>(GPL-3.0 OR LGPL-3.0 OR MPL-1.1)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-PH"
						><code>dictionary-es-ph</code></a
					></td
				>
				<td>Spanish (or Castilian; Philippines)</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-PH/license"
						>(GPL-3.0 OR LGPL-3.0 OR MPL-1.1)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-PR"
						><code>dictionary-es-pr</code></a
					></td
				>
				<td>Spanish (or Castilian; Puerto Rico)</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-PR/license"
						>(GPL-3.0 OR LGPL-3.0 OR MPL-1.1)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-PY"
						><code>dictionary-es-py</code></a
					></td
				>
				<td>Spanish (or Castilian; Paraguay)</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-PY/license"
						>(GPL-3.0 OR LGPL-3.0 OR MPL-1.1)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-SV"
						><code>dictionary-es-sv</code></a
					></td
				>
				<td>Spanish (or Castilian; El Salvador)</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-SV/license"
						>(GPL-3.0 OR LGPL-3.0 OR MPL-1.1)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-US"
						><code>dictionary-es-us</code></a
					></td
				>
				<td>Spanish (or Castilian; United States)</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-US/license"
						>(GPL-3.0 OR LGPL-3.0 OR MPL-1.1)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-UY"
						><code>dictionary-es-uy</code></a
					></td
				>
				<td>Spanish (or Castilian; Uruguay)</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-UY/license"
						>(GPL-3.0 OR LGPL-3.0 OR MPL-1.1)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-VE"
						><code>dictionary-es-ve</code></a
					></td
				>
				<td>Spanish (or Castilian; Venezuela)</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/es-VE/license"
						>(GPL-3.0 OR LGPL-3.0 OR MPL-1.1)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/et"
						><code>dictionary-et</code></a
					></td
				>
				<td>Estonian</td>
				<td>LGPL-2.1</td>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/eu"
						><code>dictionary-eu</code></a
					></td
				>
				<td>Basque</td>
				<td>GPL-2.0</td>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/fa"
						><code>dictionary-fa</code></a
					></td
				>
				<td>Persian</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/fa/license"
						>Apache-2.0</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/fo"
						><code>dictionary-fo</code></a
					></td
				>
				<td>Faroese</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/fo/license"
						>(GPL-2.0 OR LGPL-2.1 OR MPL-1.1)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/fr"
						><code>dictionary-fr</code></a
					></td
				>
				<td>French</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/fr/license"
						>MPL-2.0</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/fur"
						><code>dictionary-fur</code></a
					></td
				>
				<td>Friulian</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/fur/license"
						>GPL-2.0</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/fy"
						><code>dictionary-fy</code></a
					></td
				>
				<td>Western Frisian</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/fy/license"
						>GPL-3.0</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/ga"
						><code>dictionary-ga</code></a
					></td
				>
				<td>Irish</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/ga/license"
						>GPL-2.0</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/gd"
						><code>dictionary-gd</code></a
					></td
				>
				<td>Scottish Gaelic (or Gaelic)</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/gd/license"
						>GPL-3.0</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/gl"
						><code>dictionary-gl</code></a
					></td
				>
				<td>Galician</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/gl/license"
						>GPL-3.0</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/he"
						><code>dictionary-he</code></a
					></td
				>
				<td>Hebrew</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/he/license"
						>AGPL-3.0</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/hr"
						><code>dictionary-hr</code></a
					></td
				>
				<td>Croatian</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/hr/license"
						>(LGPL-2.1 OR SISSL)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/hu"
						><code>dictionary-hu</code></a
					></td
				>
				<td>Hungarian</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/hu/license"
						>(GPL-2.0 OR LGPL-2.1 OR MPL-1.1)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/hy"
						><code>dictionary-hy</code></a
					></td
				>
				<td>Armenian</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/hy/license"
						>(GPL-2.0 OR LGPL-2.1 OR MPL-1.1)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/hyw"
						><code>dictionary-hyw</code></a
					></td
				>
				<td>Western Armenian</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/hyw/license"
						>(GPL-2.0 OR LGPL-2.1 OR MPL-1.1)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/ia"
						><code>dictionary-ia</code></a
					></td
				>
				<td>Interlingua</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/ia/license"
						>GPL-3.0</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/ie"
						><code>dictionary-ie</code></a
					></td
				>
				<td>Interlingue (or Occidental)</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/ie/license"
						>Apache-2.0</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/is"
						><code>dictionary-is</code></a
					></td
				>
				<td>Icelandic</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/is/license"
						>CC-BY-SA-3.0</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/it"
						><code>dictionary-it</code></a
					></td
				>
				<td>Italian</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/it/license"
						>GPL-3.0</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/ka"
						><code>dictionary-ka</code></a
					></td
				>
				<td>Georgian</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/ka/license"
						>MIT</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/ko"
						><code>dictionary-ko</code></a
					></td
				>
				<td>Korean</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/ko/license"
						>(GPL-2.0 OR LGPL-2.1 OR MPL-1.1)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/la"
						><code>dictionary-la</code></a
					></td
				>
				<td>Latin</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/la/license"
						>GPL-2.0</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/lb"
						><code>dictionary-lb</code></a
					></td
				>
				<td>Luxembourgish (or Letzeburgesch)</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/lb/license"
						>EUPL-1.1</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/lt"
						><code>dictionary-lt</code></a
					></td
				>
				<td>Lithuanian</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/lt/license"
						>BSD-3-Clause</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/ltg"
						><code>dictionary-ltg</code></a
					></td
				>
				<td>Latgalian</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/ltg/license"
						>LGPL-2.1</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/lv"
						><code>dictionary-lv</code></a
					></td
				>
				<td>Latvian</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/lv/license"
						>LGPL-2.1</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/mk"
						><code>dictionary-mk</code></a
					></td
				>
				<td>Macedonian</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/mk/license"
						>GPL-3.0</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/mn"
						><code>dictionary-mn</code></a
					></td
				>
				<td>Mongolian</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/mn/license"
						>GPL-2.0</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/nb"
						><code>dictionary-nb</code></a
					></td
				>
				<td>Norwegian Bokmål</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/nb/license"
						>GPL-2.0</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/nds"
						><code>dictionary-nds</code></a
					></td
				>
				<td>Low German (or Low Saxon)</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/nds/license"
						>GPL-3.0</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/ne"
						><code>dictionary-ne</code></a
					></td
				>
				<td>Nepali</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/ne/license"
						>LGPL-2.1</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/nl"
						><code>dictionary-nl</code></a
					></td
				>
				<td>Dutch (or Flemish)</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/nl/license"
						>(BSD-3-Clause OR CC-BY-3.0)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/nn"
						><code>dictionary-nn</code></a
					></td
				>
				<td>Norwegian Nynorsk</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/nn/license"
						>GPL-2.0</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/oc"
						><code>dictionary-oc</code></a
					></td
				>
				<td>Occitan (post 1500)</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/oc/license"
						>GPL-2.0</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/pl"
						><code>dictionary-pl</code></a
					></td
				>
				<td>Polish</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/pl/license"
						>(GPL-3.0 OR LGPL-3.0 OR MPL-2.0)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/pt"
						><code>dictionary-pt</code></a
					></td
				>
				<td>Portuguese</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/pt/license"
						>(LGPL-3.0 OR MPL-2.0)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/pt-PT"
						><code>dictionary-pt-pt</code></a
					></td
				>
				<td>Portuguese (Portugal)</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/pt-PT/license"
						>(GPL-2.0 OR LGPL-2.1 OR MPL-1.1)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/ro"
						><code>dictionary-ro</code></a
					></td
				>
				<td>Romanian (or Moldavian; or Moldovan)</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/ro/license"
						>(GPL-2.0 OR LGPL-2.1 OR MPL-1.1)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/ru"
						><code>dictionary-ru</code></a
					></td
				>
				<td>Russian</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/ru/license"
						>LGPL-3.0</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/rw"
						><code>dictionary-rw</code></a
					></td
				>
				<td>Kinyarwanda</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/rw/license"
						>GPL-3.0</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/sk"
						><code>dictionary-sk</code></a
					></td
				>
				<td>Slovak</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/sk/license"
						>(GPL-2.0 OR LGPL-2.1 OR MPL-1.1)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/sl"
						><code>dictionary-sl</code></a
					></td
				>
				<td>Slovenian</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/sl/license"
						>(GPL-3.0 OR LGPL-2.1)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/sr"
						><code>dictionary-sr</code></a
					></td
				>
				<td>Serbian</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/sr/license"
						>(GPL-2.0 OR LGPL-2.1 OR MPL-1.1 OR CC-BY-SA-3.0)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/sr-Latn"
						><code>dictionary-sr-latn</code></a
					></td
				>
				<td>Serbian (Latin script)</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/sr-Latn/license"
						>(GPL-2.0 OR LGPL-2.1 OR MPL-1.1 OR CC-BY-SA-3.0)</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/sv"
						><code>dictionary-sv</code></a
					></td
				>
				<td>Swedish</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/sv/license"
						>LGPL-3.0</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/sv-FI"
						><code>dictionary-sv-fi</code></a
					></td
				>
				<td>Swedish (Finland)</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/sv-FI/license"
						>LGPL-3.0</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/tk"
						><code>dictionary-tk</code></a
					></td
				>
				<td>Turkmen</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/tk/license"
						>Apache-2.0</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/tlh"
						><code>dictionary-tlh</code></a
					></td
				>
				<td>Klingon (or tlhIngan Hol)</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/tlh/license"
						>Apache-2.0</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/tlh-Latn"
						><code>dictionary-tlh-latn</code></a
					></td
				>
				<td>Klingon (or tlhIngan Hol; Latin script)</td>
				<td
					><a
						href="/wooorm/dictionaries/blob/main/dictionaries/tlh-Latn/license"
						>Apache-2.0</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/tr"
						><code>dictionary-tr</code></a
					></td
				>
				<td>Turkish</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/tr/license"
						>MIT</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/uk"
						><code>dictionary-uk</code></a
					></td
				>
				<td>Ukrainian</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/uk/license"
						>GPL-3.0</a
					></td
				>
			</tr>
			<tr>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/vi"
						><code>dictionary-vi</code></a
					></td
				>
				<td>Vietnamese</td>
				<td
					><a
						href="https://github.com/wooorm/dictionaries/blob/main/dictionaries/vi/license"
						>GPL-2.0</a
					></td
				>
			</tr>
		</tbody>
	</table>
</main>

<style lang="scss">
	main {
		text-align: left;
		gap: 2rem;
		padding: 2rem 1rem;
		min-height: calc(var(--vh, 1vh) * 100);
		max-width: 768px;
		margin: 0 auto;
	}

	header {
		display: flex;
		flex-direction: row;
		align-items: center;
		justify-content: space-between;
	}
</style>
